example:
  key_label: ImportedKey
  id: 1
properties:
  key_label:
    description: Label of the key to delete
    example: ImportedKey
    maxLength: 256
    minLength: 1
    type: string
  id:
    description: Key identifier (optional)
    example: 1
    maxLength: 64
    type: integer
required:
- id
- key_label
type: object
