example:
  key_label: MySecretKey
  plain: 48656c6c6f20576f726c6421
  encryption_algorithm: 1
description: Request schema for encrypting data using a specified key and algorithm
properties:
  key_label:
    description: Label of the key to encrypt
    example: MySecretKey
    minLength: 1
    type: string
  plain:
    description: Data to encrypt encoded in hexadecimal
    example: !!binary |-
      NDg2NTZjNmM2ZjIwNTc2ZjcyNmM2NDIx
    format: byte
    type: string
  encryption_algorithm:
    description: "Encryption algorithm to use (1: AES, 2: AES, 3: DES, 4: DES3)"
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    example: 1
    type: integer
required:
- encryption_algorithm
- key_label
- plain
type: object
