example:
  plain: 48656c6c6f20576f726c6421
  ok: true
  time_created: 2024-10-03T10:15:30Z
  time_updated: 2024-10-03T10:15:30Z
properties:
  plain:
    description: Decrypted plaintext data in hexadecimal
    example: !!binary |-
      NDg2NTZjNmM2ZjIwNTc2ZjcyNmM2NDIx
    format: byte
    type: string
  id:
    description: ID of the key that was used to decrypt the data
    example: 1
    type: integer
  ok:
    description: Indicates if the operation was successful
    example: true
    type: boolean
  time_created:
    description: Creation timestamp in RFC3339 format
    example: 2024-10-03T10:15:30Z
    format: date-time
    type: string
  time_updated:
    description: Update timestamp in RFC3339 format
    example: 2024-10-03T10:15:30Z
    format: date-time
    type: string
type: object
