example:
  handle: 123456789
  id: 2
properties:
  handle:
    description: HSM key handle
    example: 123456789
    type: integer
  id:
    description: Key identifier
    example: 3
    type: integer
type: object
