example:
  keys:
    - handle: 1001
      id: 1
      size_bits: 256
    - handle: 1002
      id: 2
      size_bits: 256
properties:
  keys:
    description: Array of key information
    items:
      $ref: '#/components/schemas/DataKeyInfo'
    type: array
required:
- keys
type: object
