example:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  token_type: Bearer
  expires_in: 3600
properties:
  token:
    description: JWT access token
    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    type: string
  message:
    description: Token type
    example: Bearer
    type: string
  # expires_in:
  #   description: Token expiration time in seconds
  #   example: 3600
  #   type: integer
required:
- token
- token_type
# - expires_in
type: object
